### ISSUE TITLE
Dependencies version

### ISSUE THREAD

**Issue by alemela** [jindrichmynarz/rdf-path-examples#1]
Could you please provide the versions for dependencies? I'm trying with `clojure 1.6.0`, `Leiningen 2.6.1 on Java 1.7.0_80 Java HotSpot(TM) 64-Bit Server VM` and compilation failed:

```
Exception in thread "main" java.lang.UnsupportedClassVersionError: org/apache/jena/rdf/model/Literal : Unsupported major.minor version 52.0, compiling:(sparql.clj:1:1)
```

Thanks!

**Comment by jindrichmynarz** [comment]
The code requires Java 1.8 (tested with 1.8.0_74). I'm sorry this wasn't explicitly documented. Now I added this into the `project.clj`.

**Comment by alemela** [comment]
Many thanks!
